-- ============================================================================
-- Tu Repo · Esquema de la base de datos (Supabase / PostgreSQL)
-- ----------------------------------------------------------------------------
-- Reconstruye TODA la estructura: tablas, índices, vistas, funciones (RPC),
-- triggers y políticas RLS. Pensado para recrear el proyecto desde cero si
-- se corrompe o se borra. NO incluye datos de usuarios (solo estructura).
--
-- Orden de ejecución pensado para correrse de arriba a abajo en el SQL Editor.
-- Última actualización del dump: 2026-06-21
-- Ver db/README.md para cómo restaurar y notas (storage, secrets).
-- ============================================================================

create extension if not exists pgcrypto;  -- gen_random_uuid()

-- ============================================================================
-- 1) TABLAS
-- ============================================================================

create table if not exists public.perfiles (
  id               uuid primary key references auth.users(id) on delete cascade,
  username         text,
  puntos           integer not null default 0,
  referido_por     text,
  created_at       timestamptz not null default now(),
  posts_ilimitados boolean not null default false,
  es_admin         boolean not null default false,
  foto_solicitada  boolean not null default false,
  referido_premiado boolean default false
);

create table if not exists public.reportes (
  id            uuid primary key default gen_random_uuid(),
  tipo          text not null,
  zona          text,
  estado        text,
  producto      text,
  precio        numeric,
  lugar         text,
  votos_ok      integer not null default 0,
  votos_no      integer not null default 0,
  created_at    timestamptz not null default now(),
  autor         text,
  autor_nivel   integer,
  region        text,
  comentarios_n integer not null default 0,
  detalle       text,
  foto_path     text,
  lat           double precision,
  lng           double precision
);

create table if not exists public.fotos (
  id            uuid primary key default gen_random_uuid(),
  region        text not null,
  categoria     text,
  descripcion   text,
  storage_path  text not null,
  estado        text not null default 'pendiente',
  autor         text,
  autor_nivel   integer,
  created_at    timestamptz not null default now(),
  aprobada_at   timestamptz,
  comentarios_n integer not null default 0,
  corazones     integer not null default 0,
  reporte_id    uuid,
  reporte_label text
);

create table if not exists public.comentarios (
  id          uuid primary key default gen_random_uuid(),
  tipo        text not null,
  ref_id      uuid not null,
  texto       text not null,
  autor       text,
  autor_nivel integer,
  created_at  timestamptz not null default now(),
  constraint comentarios_tipo_check  check (tipo = any (array['reporte'::text, 'foto'::text])),
  constraint comentarios_texto_check check (char_length(texto) <= 100)
);

create table if not exists public.lugares (
  id         bigint generated by default as identity primary key,
  tipo       text not null,
  nombre     text not null,
  clave      text not null,
  menciones  integer not null default 1,
  created_at timestamptz not null default now(),
  region     text,
  lat        double precision,   -- ubicación recordada (si la comunidad la marcó)
  lng        double precision,
  constraint lugares_region_tipo_clave_key unique (region, tipo, clave)
);

create table if not exists public.noticias (
  id        bigint generated by default as identity primary key,
  titulo    text not null,
  enlace    text not null unique,
  fuente    text,
  categoria text,
  publicado timestamptz,
  creado    timestamptz not null default now()
);

create table if not exists public.tasa_bcv (
  id          integer primary key default 1,
  valor       numeric not null,
  actualizado timestamptz not null default now(),
  constraint tasa_bcv_id_check check (id = 1)
);

create table if not exists public.tasa_binance (
  id          integer primary key,
  valor       numeric,
  actualizado timestamptz not null default now()
);

-- Registro para rate limiting (solo lo tocan funciones SECURITY DEFINER)
create table if not exists public.rate_limit (
  ident  text not null,
  accion text not null,
  at     timestamptz not null default now()
);

-- Observabilidad: errores del cliente en producción (insert público, lectura solo admin/service_role)
create table if not exists public.error_log (
  id         uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  contexto   text,
  mensaje    text,
  detalle    text,
  url        text,
  user_agent text,
  username   text
);

-- ============================================================================
-- 2) ÍNDICES (además de los PK/UNIQUE implícitos)
-- ============================================================================

create index if not exists idx_reportes_tipo_fecha on public.reportes using btree (tipo, created_at desc);
create index if not exists comentarios_ref          on public.comentarios using btree (tipo, ref_id, created_at);
create index if not exists idx_lugares_tipo         on public.lugares using btree (tipo, menciones desc);
create index if not exists noticias_publicado_idx   on public.noticias using btree (publicado desc);
create index if not exists rate_limit_lookup        on public.rate_limit using btree (ident, accion, at);
create index if not exists error_log_fecha          on public.error_log using btree (created_at desc);

-- ============================================================================
-- 3) FUNCIONES (RPC) — todas SECURITY DEFINER con search_path fijo
-- ============================================================================

-- Crea el perfil al registrarse un usuario (lo dispara el trigger en auth.users)
create or replace function public.crear_perfil()
returns trigger language plpgsql security definer set search_path to 'public'
as $$
begin
  insert into public.perfiles(id, username, referido_por)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'referido_por');
  return new;
end; $$;

-- Rate limiting: identifica por usuario (con sesión) o IP (anónimo); admins exentos
create or replace function public.check_rate_limit(p_accion text, p_max int, p_minutos int)
returns void language plpgsql security definer set search_path to 'public'
as $$
declare v_ident text; v_ip text; v_count int;
begin
  if auth.uid() is not null
     and coalesce((select es_admin from perfiles where id = auth.uid()), false) then
    return;  -- los admins no tienen límite
  end if;
  if auth.uid() is not null then
    v_ident := 'u:' || auth.uid()::text;
  else
    v_ip := split_part(coalesce(nullif(current_setting('request.headers', true),'')::json ->> 'x-forwarded-for',''), ',', 1);
    v_ident := 'ip:' || coalesce(nullif(trim(v_ip),''), 'desconocido');
  end if;
  delete from public.rate_limit where ident = v_ident and at < now() - interval '1 hour';
  select count(*) into v_count from public.rate_limit
   where ident = v_ident and accion = p_accion and at > now() - make_interval(mins => p_minutos);
  if v_count >= p_max then
    raise exception 'Vas muy rápido. Espera unos minutos e intenta de nuevo.';
  end if;
  insert into public.rate_limit(ident, accion) values (v_ident, p_accion);
end; $$;

-- Deriva autor/autor_nivel desde auth.uid() (anti-suplantación) + rate limit.
-- Lo usan los triggers BEFORE INSERT de reportes y fotos.
create or replace function public.set_autor_real()
returns trigger language plpgsql security definer set search_path to 'public'
as $$
declare v_user text; v_pts int;
begin
  if tg_table_name = 'reportes' then
    perform public.check_rate_limit('reporte', case when auth.uid() is not null then 3 else 2 end, 15);
  elsif tg_table_name = 'fotos' then
    perform public.check_rate_limit('foto', case when auth.uid() is not null then 3 else 2 end, 15);
  end if;
  if auth.uid() is null then
    new.autor := null; new.autor_nivel := null;
  else
    select username, puntos into v_user, v_pts from public.perfiles where id = auth.uid();
    new.autor := v_user;
    new.autor_nivel := case when v_pts>=1000 then 4 when v_pts>=400 then 3
                            when v_pts>=150 then 2 when v_pts>=50 then 1 else 0 end;
  end if;
  return new;
end; $$;

-- Elegir/cambiar username (valida formato y unicidad)
create or replace function public.elegir_username(p_username text)
returns text language plpgsql security definer set search_path to 'public'
as $$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null then return 'no_auth'; end if;
  if p_username !~ '^[A-Za-z0-9_]{3,20}$' then return 'formato'; end if;
  if exists(select 1 from public.perfiles where lower(username)=lower(p_username) and id<>v_uid)
     then return 'taken'; end if;
  update public.perfiles set username=p_username where id=v_uid;
  if not found then insert into public.perfiles(id,username) values(v_uid,p_username); end if;
  return 'ok';
end; $$;

-- Suma puntos al usuario actual (monto fijo, ignora cualquier n del cliente)
create or replace function public.sumar_mis_puntos(n integer)
returns integer language plpgsql security definer set search_path to 'public'
as $$
declare nuevo int;
begin
  if auth.uid() is null then return null; end if;
  update perfiles set puntos = puntos + 10 where id = auth.uid() returning puntos into nuevo;
  return nuevo;
end; $$;

-- Premia al referidor, una sola vez, validando el referido_por real del que llama
create or replace function public.puntos_por_referido(ref text)
returns void language plpgsql security definer set search_path to 'public'
as $$
declare v_ya boolean; v_ref text;
begin
  if auth.uid() is null then return; end if;
  select referido_premiado, referido_por into v_ya, v_ref from perfiles where id = auth.uid();
  if v_ya is true or v_ref is null or lower(v_ref) <> lower(ref) then return; end if;
  update perfiles set puntos = puntos + 20 where lower(username) = lower(ref);
  update perfiles set referido_premiado = true where id = auth.uid();
end; $$;

-- Registra/incrementa un lugar mencionado (y recuerda su ubicación si viene)
create or replace function public.registrar_lugar(p_region text, p_tipo text, p_nombre text, p_clave text,
  p_lat double precision default null, p_lng double precision default null)
returns integer language plpgsql security definer set search_path to 'public'
as $$
declare total int;
begin
  insert into lugares (region, tipo, nombre, clave, lat, lng)
  values (p_region, p_tipo, p_nombre, p_clave, p_lat, p_lng)
  on conflict (region, tipo, clave)
  do update set menciones = lugares.menciones + 1,
                lat = coalesce(excluded.lat, lugares.lat),
                lng = coalesce(excluded.lng, lugares.lng)
  returning menciones into total;
  return total;
end; $$;

-- Votar un reporte (sube votos_ok/votos_no)
create or replace function public.votar(reporte uuid, ok boolean)
returns void language sql security definer set search_path to 'public'
as $$
  update reportes
     set votos_ok = votos_ok + (case when ok then 1 else 0 end),
         votos_no = votos_no + (case when ok then 0 else 1 end)
   where id = reporte;
$$;

-- Comentar (deriva autor de auth.uid(), valida y aplica rate limit)
create or replace function public.comentar(p_tipo text, p_ref uuid, p_texto text,
  p_autor text default null, p_autor_nivel integer default null)
returns void language plpgsql security definer set search_path to 'public'
as $$
declare v_user text; v_pts int;
begin
  if p_tipo not in ('reporte','foto') then raise exception 'tipo inválido'; end if;
  if p_texto is null or char_length(trim(p_texto)) < 2 or char_length(p_texto) > 100 then
    raise exception 'texto inválido (2 a 100 caracteres)'; end if;
  perform public.check_rate_limit('comentario', case when auth.uid() is not null then 6 else 3 end, 15);
  select username, puntos into v_user, v_pts from public.perfiles where id = auth.uid();
  insert into comentarios (tipo, ref_id, texto, autor, autor_nivel)
  values (p_tipo, p_ref, trim(p_texto), v_user,
          case when v_user is null then null
               when v_pts>=1000 then 4 when v_pts>=400 then 3
               when v_pts>=150 then 2 when v_pts>=50 then 1 else 0 end);
  if p_tipo = 'reporte' then
    update reportes set comentarios_n = comentarios_n + 1 where id = p_ref;
  else
    update fotos set comentarios_n = comentarios_n + 1 where id = p_ref;
  end if;
end; $$;

-- Like a una foto aprobada
create or replace function public.reaccionar_foto(foto_id uuid)
returns void language sql security definer set search_path to 'public'
as $$
  update fotos set corazones = corazones + 1 where id = foto_id and estado = 'aprobada';
$$;

-- Borrar mi propio reporte (devuelve los storage_path de sus fotos para limpiar)
create or replace function public.borrar_mi_reporte(rid uuid)
returns text[] language plpgsql security definer set search_path to 'public'
as $$
declare v_yo text; v_paths text[];
begin
  select p.username into v_yo from public.perfiles p where p.id = auth.uid();
  select array_agg(f.storage_path) into v_paths from public.fotos f where f.reporte_id = rid;
  delete from public.reportes r where r.id = rid and r.autor is not null and r.autor = v_yo;
  if not found then return null; end if;
  delete from public.fotos f where f.reporte_id = rid;
  return v_paths;
end; $$;

-- Borrar mi propia foto (devuelve el storage_path para limpiar)
create or replace function public.borrar_mi_foto(foto_id uuid)
returns text language plpgsql security definer set search_path to 'public'
as $$
declare v_yo text; v_path text;
begin
  select p.username into v_yo from public.perfiles p where p.id = auth.uid();
  delete from public.fotos f where f.id = foto_id and f.autor is not null and f.autor = v_yo
   returning f.storage_path into v_path;
  return v_path;
end; $$;

-- Usuario pide permiso para subir fotos (lo revisa un admin)
create or replace function public.solicitar_foto()
returns void language plpgsql security definer set search_path to 'public'
as $$
begin
  update public.perfiles set foto_solicitada = true
   where id = auth.uid() and coalesce(posts_ilimitados,false) = false;
end; $$;

-- Publicar foto en un reporte (solo usuarios con posts_ilimitados)
create or replace function public.publicar_foto_reporte(p_path text, p_label text, p_reporte uuid, p_region text, p_autor text, p_nivel integer)
returns void language plpgsql security definer set search_path to 'public'
as $$
begin
  if not exists (select 1 from public.perfiles where id = auth.uid() and coalesce(posts_ilimitados,false) = true) then
    raise exception 'Sin permiso para publicar fotos';
  end if;
  insert into public.fotos (region, storage_path, estado, aprobada_at, autor, autor_nivel, reporte_id, reporte_label)
  values (p_region, p_path, 'aprobada', now(), p_autor, p_nivel, p_reporte, p_label);
  update public.reportes set foto_path = p_path where id = p_reporte;
end; $$;

-- ---- Funciones de admin (validan es_admin por dentro) ----

create or replace function public.aprobar_foto(foto_id uuid)
returns void language plpgsql security definer set search_path to 'public'
as $$
begin
  if not coalesce((select es_admin from perfiles where id = auth.uid()), false) then
    raise exception 'No autorizado';
  end if;
  update fotos set estado = 'aprobada', aprobada_at = now()
  where id = foto_id and estado = 'pendiente';
end $$;

create or replace function public.rechazar_foto(foto_id uuid)
returns void language plpgsql security definer set search_path to 'public'
as $$
begin
  if not coalesce((select es_admin from perfiles where id = auth.uid()), false) then
    raise exception 'No autorizado';
  end if;
  delete from fotos where id = foto_id;  -- el archivo lo borra la app vía Storage
end $$;

create or replace function public.fotos_pendientes()
returns setof public.fotos language plpgsql security definer set search_path to 'public'
as $$
begin
  if not coalesce((select es_admin from perfiles where id = auth.uid()), false) then
    raise exception 'No autorizado';
  end if;
  return query select * from fotos where estado = 'pendiente' order by created_at asc;
end $$;

create or replace function public.aprobar_foto_usuario(uid uuid)
returns void language plpgsql security definer set search_path to 'public'
as $$
begin
  if not exists (select 1 from public.perfiles p where p.id = auth.uid() and p.es_admin) then
    raise exception 'No autorizado';
  end if;
  update public.perfiles p set posts_ilimitados = true, foto_solicitada = false where p.id = uid;
end; $$;

create or replace function public.solicitudes_foto()
returns table(id uuid, username text, puntos integer) language plpgsql security definer set search_path to 'public'
as $$
begin
  if not exists (select 1 from public.perfiles p where p.id = auth.uid() and p.es_admin) then
    raise exception 'No autorizado';
  end if;
  return query
    select p.id, p.username, p.puntos from public.perfiles p
    where p.foto_solicitada = true and coalesce(p.posts_ilimitados,false) = false
    order by p.username;
end; $$;

-- Safety: activa RLS automáticamente en tablas nuevas de public
create or replace function public.rls_auto_enable()
returns event_trigger language plpgsql security definer set search_path to 'pg_catalog'
as $$
declare cmd record;
begin
  for cmd in
    select * from pg_event_trigger_ddl_commands()
    where command_tag in ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      and object_type in ('table','partitioned table')
  loop
    if cmd.schema_name is not null and cmd.schema_name = 'public' then
      begin
        execute format('alter table if exists %s enable row level security', cmd.object_identity);
      exception when others then null;
      end;
    end if;
  end loop;
end; $$;

-- ============================================================================
-- 4) TRIGGERS
-- ============================================================================

drop trigger if exists al_crear_usuario on auth.users;
create trigger al_crear_usuario
  after insert on auth.users
  for each row execute function public.crear_perfil();

drop trigger if exists trg_reportes_autor on public.reportes;
create trigger trg_reportes_autor
  before insert on public.reportes
  for each row execute function public.set_autor_real();

drop trigger if exists trg_fotos_autor on public.fotos;
create trigger trg_fotos_autor
  before insert on public.fotos
  for each row execute function public.set_autor_real();

-- Event trigger que activa RLS en tablas nuevas (nombre aproximado; inofensivo)
drop event trigger if exists trg_rls_auto_enable;
create event trigger trg_rls_auto_enable on ddl_command_end
  execute function public.rls_auto_enable();

-- ============================================================================
-- 5) VISTAS (contenido "activo" = últimas 12 horas)
-- ============================================================================

create or replace view public.reportes_activos as
  select id, tipo, zona, estado, producto, precio, lugar, votos_ok, votos_no,
         created_at, autor, autor_nivel, region, comentarios_n, detalle, foto_path, lat, lng
  from public.reportes
  where created_at > (now() - interval '12 hours')
    and not (votos_no >= 5 and votos_no > (votos_ok + 2));

create or replace view public.fotos_activas as
  select id, region, categoria, descripcion, storage_path, autor, autor_nivel,
         created_at, aprobada_at, corazones, comentarios_n, reporte_id, reporte_label
  from public.fotos
  where estado = 'aprobada' and aprobada_at > (now() - interval '12 hours');

-- ============================================================================
-- 6) RLS + POLÍTICAS
-- ============================================================================

alter table public.perfiles     enable row level security;
alter table public.reportes     enable row level security;
alter table public.fotos        enable row level security;
alter table public.comentarios  enable row level security;
alter table public.lugares      enable row level security;
alter table public.noticias     enable row level security;
alter table public.tasa_bcv     enable row level security;
alter table public.tasa_binance enable row level security;
alter table public.rate_limit   enable row level security;  -- sin políticas: solo SECURITY DEFINER
alter table public.error_log    enable row level security;

-- error_log: el cliente puede INSERTAR errores; nadie los LEE salvo admin/service_role
drop policy if exists error_log_insert on public.error_log;
create policy error_log_insert on public.error_log for insert to anon, authenticated with check (true);

-- perfiles: lectura pública; SIN update directo (los cambios van por RPC SECURITY DEFINER)
drop policy if exists perfil_leer on public.perfiles;
create policy perfil_leer on public.perfiles for select to public using (true);

-- reportes: lectura pública; insertar permitido (el trigger fija el autor real)
drop policy if exists leer_todos on public.reportes;
create policy leer_todos on public.reportes for select to anon, authenticated using (true);
drop policy if exists insertar_anon on public.reportes;
create policy insertar_anon on public.reportes for insert to anon, authenticated with check (true);

-- fotos: solo se leen las aprobadas; al insertar se fuerza estado 'pendiente'
drop policy if exists fotos_leer_aprobadas on public.fotos;
create policy fotos_leer_aprobadas on public.fotos for select to anon, authenticated using (estado = 'aprobada');
drop policy if exists fotos_insertar on public.fotos;
create policy fotos_insertar on public.fotos for insert to anon, authenticated with check (estado = 'pendiente');

-- comentarios: lectura pública (escritura solo por RPC comentar)
drop policy if exists comentarios_leer on public.comentarios;
create policy comentarios_leer on public.comentarios for select to anon, authenticated using (true);

-- lugares: lectura pública (escritura solo por RPC registrar_lugar)
drop policy if exists lugares_leer on public.lugares;
create policy lugares_leer on public.lugares for select to public using (true);

-- noticias / tasas: lectura pública (escritura solo service_role por los Actions)
drop policy if exists "Lectura publica de noticias" on public.noticias;
create policy "Lectura publica de noticias" on public.noticias for select to anon, authenticated using (true);
drop policy if exists "lectura publica tasa_bcv" on public.tasa_bcv;
create policy "lectura publica tasa_bcv" on public.tasa_bcv for select to anon, authenticated using (true);
drop policy if exists "Lectura publica de tasa_binance" on public.tasa_binance;
create policy "Lectura publica de tasa_binance" on public.tasa_binance for select to anon, authenticated using (true);

-- ============================================================================
-- 7) PERMISOS
-- ============================================================================

-- check_rate_limit es interna (la llaman triggers/RPC), no debe llamarla el cliente
revoke execute on function public.check_rate_limit(text,int,int) from anon, authenticated;
